### ISSUE TITLE
Worked after comma replacement in match records, then stopped working again.

### ISSUE THREAD

**Issue by jossimo** [synkarius/saltbot#100]
Worked for about a day. then stopped working again, getting error when it opens, trying to update weights and when trying to view match data through extension. Using same records that I posted in last thread, but with comma fix in character name. Tried importing the original seed data I downloaded from here and same errors.
[saltyRecordsM--2016-6-11-10.46.txt](https://github.com/synkarius/saltbot/files/318544/saltyRecordsM--2016-6-11-10.46.txt)
[chromosome--2016-6-11-10.45.txt](https://github.com/synkarius/saltbot/files/318546/chromosome--2016-6-11-10.45.txt)

Thanks again for your help!

**Error when it opens**
extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'limit_enabled' of undefined
    at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:493:44)
    at HTMLDocument.<anonymous> (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:491:23)handler @ extensions::uncaught_exception_handler:8
popup.html:1 Alarm delay is less than minimum of 1 minutes. Alarm "chromosome update" will fire in approximately 1 minutes.

**Error when trying to update weights:**
extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:256:30)
    at Simulator.evalMutations (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:181:23)
    at HTMLDivElement.<anonymous> (chrome-extension://bholoegapebhflljekancpcnajigaiih/popup.js:506:13)handler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100safeCallbackApply @ extensions::sendRequest:23handleResponse @ extensions::sendRequest:74

**Error when clicking table icon to view match data**
extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'concat' of undefined
    at Object.callback (chrome-extension://bholoegapebhflljekancpcnajigaiih/matchdata.js:40:19)
    at chrome-extension://bholoegapebhflljekancpcnajigaiih/matchdata.js:22:22handler @ extensions::uncaught_exception_handler:8

**Comment by reconman** [comment]
Your match data got deleted somehow but I have no idea how. I've looked through the code twice and at no point the matches can be set to nothing. I couldn't reproduce it at all.

I pushed an update so I can get the bot working again with your corrupted match data. In the second and third error the bot has no matches to work with.

Still your extension settings somehow got changed and I can't say how.

**Comment by reconman** [comment]
One quick question, do you press update genetic weights immediately after the record import or do you wait a few seconds until the import is finished like you're supposed to?

**Comment by jossimo** [comment]
I give it a second before hitting update generic weights, but I'll give it a 5 Mississippi next time. At work, so later this eve and will let you know. 
Thanks!

**Comment by reconman** [comment]
Open the console while importing and press update weights after you see the import message with "x matches, y characters were imported."

**Comment by jossimo** [comment]
Still not working...I import the above match and chromosome data, says it's successful, then when I try to update weights it says there is no match data. Console messages pasted below;

 Object
popup.html:1 Alarm delay is less than minimum of 1 minutes. Alarm "chromosome update" will fire in approximately 1 minutes.
popup.js:101 Attempting records import...
popup.js:104 Upload successful.
popup.js:107 Attempting to read file...
popup.js:91 File read successful.
popup.js:115 Attempting chromosome import...
popup.js:118 Upload successful.
popup.js:121 Attempting to read file...
popup.js:96 File read successful.
popup.js:188 No matches have been recorded yet.

**Comment by reconman** [comment]
Not the popup console. The console of the main window with saltybet is relevant.

---- On Fr, 17 Jun 2016 03:19:19 +0200 notifications@github.com wrote ----

Still not working...I import the above match and chromosome data, says it's successful, then when I try to update weights it says there is no match data. Console messages pasted below;

Object
popup.html:1 Alarm delay is less than minimum of 1 minutes. Alarm "chromosome update" will fire in approximately 1 minutes.
popup.js:101 Attempting records import...
popup.js:104 Upload successful.
popup.js:107 Attempting to read file...
popup.js:91 File read successful.
popup.js:115 Attempting chromosome import...
popup.js:118 Upload successful.
popup.js:121 Attempting to read file...
popup.js:96 File read successful.
popup.js:188 No matches have been recorded yet.

**Comment by jossimo** [comment]
This?

Activated browser action
player.9fcff8d….js:13 subscribing to unknown event:  undefinedm.addEventListener @ player.9fcff8d….js:13
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
global-0ae272a….js:17 JQMIGRATE: jQuery.browser is deprecated
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
global-0ae272a….js:30 No cast extension found
emberchat-71bacb6….js:30 Uncaught SecurityError: Blocked a frame with origin "https://www.twitch.tv" from accessing a frame with origin "http://live.saltybet.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

(program):1 build: local
s-usc1c-nss-148.firebaseio.com/.lp?dframe=t&id=2960193&pw=pmxAL2QN2w&ns=ttv-10:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
vendor.53c7d1a….js:4 XHR finished loading: GET "http://api.mixpanel.com/track?data=eyJldmVudCI6InF1YWxpdHlfY2hhbmdlX2NvbXBs…4MDk1NzY0Njg1NzIxMzRmOTA5ZGZmYTZiZDBkY2ZjZiJ9fQ%3D%3D&ip=1&_=1466147714527".send @ vendor.53c7d1a….js:4ajax @ vendor.53c7d1a….js:4o.trackEvent @ player.9fcff8d….js:10(anonymous function) @ player.9fcff8d….js:10o.trackEvents @ player.9fcff8d….js:10(anonymous function) @ player.9fcff8d….js:10(anonymous function) @ player.9fcff8d….js:10
vendor.53c7d1a….js:4 XHR finished loading: POST "http://spade.twitch.tv/".send @ vendor.53c7d1a….js:4ajax @ vendor.53c7d1a….js:4o._send @ player.9fcff8d….js:10o.trackEvents @ player.9fcff8d….js:10(anonymous function) @ player.9fcff8d….js:10(anonymous function) @ player.9fcff8d….js:10

**Comment by reconman** [comment]
Almost, those are errors produced by saltybet itself.

Please load saltybet, go to the site's console, click on the filter symbol (second icon from the left) and select "Hide network messages". That will filter out all those net::ERR_FAILED error messages.

Now look for any messages with salty.js, records.js, strategy.js or tracker.js on the right side of the message. Those come from saltbot, the others do not.

**Comment by jossimo** [comment]
This is what I see, just the first line is the only one I that has salty.js

Activated browser action                                                                       
salty.js:4
player.9fcff8d….js:13 subscribing to unknown event:  undefinedm.addEventListener @ player.9fcff8d….js:13p @ player.9fcff8d….js:22o @ player.9fcff8d….js:22Z @ player.9fcff8d….js:22o @ player.9fcff8d….js:22S @ player.9fcff8d….js:1o @ player.9fcff8d….js:1(anonymous function) @ ?channel=saltybet:1
global-0ae272a….js:17 JQMIGRATE: jQuery.browser is deprecated
global-0ae272a….js:30 No cast extension found
emberchat-352a0b6….js:30 Uncaught SecurityError: Blocked a frame with origin "https://www.twitch.tv" from accessing a frame with origin "http://live.saltybet.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
after @ emberchat-352a0b6….js:30(anonymous function) @ emberchat-352a0b6….js:7n @ emberchat-352a0b6….js:7r @ emberchat-352a0b6….js:7setHostMode @ emberchat-352a0b6….js:40(anonymous function) @ emberchat-352a0b6….js:39(anonymous function) @ global-0ae272a….js:15f @ global-0ae272a….js:15fireWith @ global-0ae272a….js:15i.(anonymous function) @ global-0ae272a….js:15(anonymous function) @ tmi-v3.rb752671….js:2f @ global-0ae272a….js:15fireWith @ global-0ae272a….js:15i.(anonymous function) @ global-0ae272a….js:15f @ global-0ae272a….js:15fireWith @ global-0ae272a….js:15x @ global-0ae272a….js:16t @ global-0ae272a….js:16
VM3093:1 build: local
VM3070 .lp?dframe=t&id=3497059&pw=3vRkdULVGm&ns=ttv-10:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM3182:1 Error: Ad adPlayError error: Error while attempting to play media. errorCode: 1104(anonymous function) @ VM3182:1
VM3183:1 Flash Backend: Uncaught error: TypeError: Error #1034

**Comment by reconman** [comment]
What happens when you try to import?

---- On Fr, 17 Jun 2016 15:54:41 +0200 notifications@github.com wrote ----

This is what I see, just the first line is the only one I that has salty.js

Activated browser action

salty.js:4
player.9fcff8d….js:13 subscribing to unknown event: undefinedm.addEventListener @ player.9fcff8d….js:13p @ player.9fcff8d….js:22o @ player.9fcff8d….js:22Z @ player.9fcff8d….js:22o @ player.9fcff8d….js:22S @ player.9fcff8d….js:1o @ player.9fcff8d….js:1(anonymous function) @ ?channel=saltybet:1
global-0ae272a….js:17 JQMIGRATE: jQuery.browser is deprecated
global-0ae272a….js:30 No cast extension found
emberchat-352a0b6….js:30 Uncaught SecurityError: Blocked a frame with origin "https://www.twitch.tv" from accessing a frame with origin "http://live.saltybet.com". The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
after @ emberchat-352a0b6….js:30(anonymous function) @ emberchat-352a0b6….js:7n @ emberchat-352a0b6….js:7r @ emberchat-352a0b6….js:7setHostMode @ emberchat-352a0b6….js:40(anonymous function) @ emberchat-352a0b6….js:39(anonymous function) @ global-0ae272a….js:15f @ global-0ae272a….js:15fireWith @ global-0ae272a….js:15i.(anonymous function) @ global-0ae272a….js:15(anonymous function) @ tmi-v3.rb752671….js:2f @ global-0ae272a….js:15fireWith @ global-0ae272a….js:15i.(anonymous function) @ global-0ae272a….js:15f @ global-0ae272a….js:15fireWith @ global-0ae272a….js:15x @ global-0ae272a….js:16t @ global-0ae272a….js:16
VM3093:1 build: local
VM3070 .lp?dframe=t&id=3497059&pw=3vRkdULVGm&ns=ttv-10:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM3182:1 Error: Ad adPlayError error: Error while attempting to play media. errorCode: 1104(anonymous function) @ VM3182:1
VM3183:1 Flash Backend: Uncaught error: TypeError: Error #1034

**Comment by jossimo** [comment]
No change, no new messages in console when trying to import any records.

**Comment by reconman** [comment]
Are you sure that nothing like

-
records imported:
38379 match records
6162 character records

appears after waiting for several seconds?

**Comment by reconman** [comment]
After looking through your log again there seems to be something wrong with your Chrome. It should display "settings upgraded" "settings applied" somewhere after activated browser action.

The code that logs this is called when chrome.storage.local.get has returned the current settings but it is asynchronous. That means that the action is executed whenever Chrome delivers the data. No data -> no call. That seems to be what is going on here.

**Comment by jossimo** [comment]
Damn, will fiddle with chrome after work and let you know. Might just uninstall/reinstall chrome and see if that does anything. Thanks again for the help.

**Comment by jossimo** [comment]
Uninstalled and reinstalled Chrome, working now...
Thanks for all your help!
